export const headerSearchInput = document.querySelector(".notes__search-icon-label");
export const searchElement = document.querySelector(".notes__searchField-wrapper");
export const searchInputLabel = document.querySelector(".notes__header-searchLabel");
export const headerMenuInput = document.getElementById("header-menu-input");
export const sidebar = document.querySelector(".notes__sidebar");
export const notesLabelSidebar = document.querySelector(".notes__notes-button");
export const notesForm = document.querySelector(".notes__form");
export const notesView = document.querySelector(".notes__view");
export const notesList = document.querySelector(".notes__list");
export const notesPreview = document.querySelector(".notes__preview");
export const addNoteLabelSidebar = document.querySelector(".notes__addNote-button");
export const titleField = document.querySelector(".notes__title-field");
export const authorField = document.querySelector(".notes__author-field");
export const noteField = document.querySelector(".notes__note-field");
export const addNoteBtn = document.querySelector(".notes__addNote-btn");
export const addPinnedBtn = document.querySelector(".notes__addPinned-btn");
export const normalNotesList = document.querySelector(".notes__notes-list");
export const pinnedNotesList = document.querySelector(".notes__pinned-list");
export const arrow = document.querySelector(".notes__arrow-wrapper");

export const getNotes = () => document.querySelectorAll(".notes__note-item");
export const getPinnedDeleteBtns = () => document.querySelectorAll(".notes__pinned-list .notes__note-delete");
export const getNormalDeleteBtns = () => document.querySelectorAll(".notes__notes-list .notes__note-delete");
